POST http://localhost:8080/films
Content-Type: application/json

{
  "title" : "Venom: Let There Be Carnage",
  "duration" : 97,
  "budget" : 110,
  "link" : "https://en.wikipedia.org/wiki/Venom:_Let_There_Be_Carnage"
}
